--- #YAML:1.0
name:                Pod-Html
version:             1.09_04
abstract:            Convert POD files to HTML
license:             perl
author:              
    - David Landgren
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Config:                        0
    Cwd:                           0
    File::Spec:                    0
    File::Spec::Unix:              0
    Getopt::Long:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
